// vscode has a suggestion to import things the ES6 way, which I expored but 
// went back to the ES5 way because we're going with tried-and-true node.js 
// methodology in this class and that is ES5 because node existed from before
// ES6
const fs = require('fs')
const path = require('path')
const inquirer = require('inquirer')
const generateMarkdown = require('./utils/generateMarkdown.js')

const licenceOptions = [
    {name:    'Apache 2.0 License',
    badge:     'https://img.shields.io/badge/License-Apache%202.0-blue.svg',
    summary:   'The Apache License is a permissive free software license written by the Apache Software Foundation (ASF).[5] It allows users to use the software for any purpose, to distribute it, to modify it, and to distribute modified versions of the software under the terms of the license, without concern for royalties. The ASF and its projects release their software products under the Apache License. The license is also used by many non-ASF projects.',
    linkToMoreInfo:'https://opensource.org/licenses/Apache-2.0'},

    {name:    'Boost Software License 1.0',
    badge:     'https://img.shields.io/badge/License-Boost%201.0-lightblue.svg',
    summary:   'This is a simple license that includes a clause on warranty, and encourages free and open use of software licensed under it. You must include the original copyright and this license in software unless in the form of “machine-executable object code generated by a source processor.”',
    linkToMoreInfo:'linkToMoreInfo'},

    {name:    'BSD 3-Clause License',
    badge:     'https://img.shields.io/badge/License-BSD%203--Clause-blue.svg',
    summary:   'Redistribution and use in source and binary forms, with or without modification, are permitted ... + 3 clauses',
    linkToMoreInfo:'linkToMoreInfo'},

    {name:    'BSD 2-Clause License',
    badge:     'https://img.shields.io/badge/License-BSD%202--Clause-orange.svg',
    summary:   'Redistribution and use in source and binary forms, with or without modification, are permitted ... +2 clauses',
    linkToMoreInfo:'https://opensource.org/licenses/BSD-2-Clause'},

    {name:  'Creative Commons 1.0',
    badge:   'https://img.shields.io/badge/License-CC0%201.0-lightgrey.svg',
    summary: 'No Copyright.  The person who associated a work with this deed has dedicated the work to the public domain by waiving all of his or her rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law. ',
    linkToMoreInfo:'http://creativecommons.org/publicdomain/zero/1.0/'},

    {name:  'Attribution 4.0 International',
    badge:   'https://img.shields.io/badge/License-CC%20BY%204.0-lightgrey.svg',
    summary: 'You are free to: Share — copy and redistribute the material in any medium or format  Adapt — remix, transform, and build upon the material for any purpose, even commercially... so long as you provide attribution ',
    linkToMoreInfo:'https://creativecommons.org/licenses/by/4.0/'},

    {name:  'Attribution-ShareAlike 4.0 International',
    badge:   'https://img.shields.io/badge/License-CC%20BY--SA%204.0-lightgrey.svg',
    summary: 'summary0',
    linkToMoreInfo:'https://creativecommons.org/licenses/by-sa/4.0/'},

    {name:  'Attribution-NonCommercial 4.0 International',
    badge:   'https://img.shields.io/badge/License-CC%20BY--NC%204.0-lightgrey.svg',
    summary: 'summary1',
    linkToMoreInfo:'https://creativecommons.org/licenses/by-nc/4.0/'},

    {name:  'Attribution-NoDerivates 4.0 International',
    badge:   'https://img.shields.io/badge/License-CC%20BY--ND%204.0-lightgrey.svg',
    summary: 'summary0',
    linkToMoreInfo:'https://creativecommons.org/licenses/by-nd/4.0/'},

    {name:  'Attribution-NonCommmercial-ShareAlike 4.0 International',
    badge:   'https://img.shields.io/badge/License-CC%20BY--NC--SA%204.0-lightgrey.svg',
    summary: 'summary1',
    linkToMoreInfo:'https://creativecommons.org/licenses/by-nc-sa/4.0/'},

    {name:  'Attribution-NonCommercial-NoDerivatives 4.0 International',
    badge:   'https://img.shields.io/badge/License-CC%20BY--NC--ND%204.0-lightgrey.svg',
    summary: 'summary0',
    linkToMoreInfo:'https://creativecommons.org/licenses/by-nc-nd/4.0/'},

    {name:  'Eclipse Public License 1.0',
    badge:   'https://img.shields.io/badge/License-EPL%201.0-red.svg',
    summary: 'summary1',
    linkToMoreInfo:'https://opensource.org/licenses/EPL-1.0'},

    {name:  'Eclipse Public License 1.0',
    badge:   'https://img.shields.io/badge/License-EPL%201.0-red.svg',
    summary: 'summary0',
    linkToMoreInfo:'https://opensource.org/licenses/EPL-1.0'},

    {name:  'GNU GPL v3',
    badge:   'https://img.shields.io/badge/License-GPLv3-blue.svg',
    summary: 'summary1',
    linkToMoreInfo:'https://www.gnu.org/licenses/gpl-3.0'},

    {name:  'GNU GPL v2',
    badge:   'https://img.shields.io/badge/License-GPL%20v2-blue.svg',
    summary: 'summary0',
    linkToMoreInfo:'https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html'},

    {name:  'GNU AGPL v3',
    badge:   'https://img.shields.io/badge/License-AGPL%20v3-blue.svg',
    summary: 'summary1',
    linkToMoreInfo:'https://www.gnu.org/licenses/agpl-3.0'},

    {name:  'GNU LGPL v3',
    badge:   'https://img.shields.io/badge/License-LGPL%20v3-blue.svg',
    summary: 'summary0',
    linkToMoreInfo:'https://www.gnu.org/licenses/lgpl-3.0'},

    {name:  'GNU FDL v1.3',
    badge:   'https://img.shields.io/badge/License-FDL%20v1.3-blue.svg',
    summary: 'summary1',
    linkToMoreInfo:'https://www.gnu.org/licenses/fdl-1.3'},

    {name:  'IBM Public License Version 1.0',
    badge:   'https://img.shields.io/badge/License-IPL%201.0-blue.svg',
    summary: 'summary1',
    linkToMoreInfo:'https://opensource.org/licenses/IPL-1.0'},

    {name:  'ISC License (ISC)',
    badge:   'https://img.shields.io/badge/License-ISC-blue.svg',
    summary: 'summary1',
    linkToMoreInfo:'https://opensource.org/licenses/ISC'},

    {name:  'The MIT License',
    badge:   'https://img.shields.io/badge/License-MIT-yellow.svg',
    summary: 'summary1',
    linkToMoreInfo:'https://opensource.org/licenses/MIT'},

    {name:  'Mozilla Public License 2.0',
    badge:   'https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg',
    summary: 'summary1',
    linkToMoreInfo:'https://opensource.org/licenses/MPL-2.0'},

    {name:  'Attribution License (BY)',
    badge:   'https://img.shields.io/badge/License-ODC_BY-brightgreen.svg',
    summary: 'summary1',
    linkToMoreInfo:'https://opendatacommons.org/licenses/by/'},

    {name:  'Open Database License (ODbL)',
    badge:   'https://img.shields.io/badge/License-ODbL-brightgreen.svg',
    summary: 'summary1',
    linkToMoreInfo:'https://opendatacommons.org/licenses/odbl/'},

    {name:  'Public Domain Dedication and License (PDDL)',
    badge:   'https://img.shields.io/badge/License-PDDL-brightgreen.svg',
    summary: 'summary1',
    linkToMoreInfo:'https://opendatacommons.org/licenses/pddl/'},

    {name:  'The Perl License AKA The Artistic License 1.0',
    badge:   'https://img.shields.io/badge/License-Perl-0298c3.svg',
    summary: 'The Artistic License is a license for open source software that was originally developed for the Perl programming language. It is now also used for a variety of other open source software as well.',
    linkToMoreInfo:'https://opensource.org/licenses/Artistic-1.0'},

    {name:  'The Artistic License 2.0',
    badge:   'https://img.shields.io/badge/License-Artistic%202.0-0298c3.svg',
    summary: 'This license establishes the terms under which a given free software Package may be copied, modified, distributed, and/or redistributed. The intent is that the Copyright Holder maintains some artistic control over the development of that Package while still keeping the Package available as open source and free software.  It is a revised version of version 1.0 of the same name and strongly recommended over it.',
    linkToMoreInfo:'https://opensource.org/licenses/Artistic-2.0'},

    {name:  'SIL Open Font License 1.1',
    badge:   'https://img.shields.io/badge/License-OFL%201.1-lightgreen.svg',
    summary: 'summary1',
    linkToMoreInfo:'https://opensource.org/licenses/OFL-1.1'},

    {name:  'The Unlicense',
    badge:   'https://img.shields.io/badge/license-Unlicense-blue.svg',
    summary: 'summary1',
    linkToMoreInfo:'http://unlicense.org/'},

    {name:  'The Do What the Fuck You Want to Public License',
    badge:   'https://img.shields.io/badge/License-WTFPL-brightgreen.svg',
    summary: 'summary1',
    linkToMoreInfo:'http://www.wtfpl.net/about/'},

    {name:  'The zlib/libpng License',
    badge:   'https://img.shields.io/badge/License-Zlib-lightgrey.svg',
    summary: 'summary1',
    linkToMoreInfo:'https://opensource.org/licenses/Zlib'},
]

var licenseChoices = licenceOptions.map(license => license.name)

// array of questions for user
var questions = [
    
    {name: 'title',
    type: 'input',
    message: "What's the title?"},
    
    {name: 'githubUser',
    type: 'input',
    message: 'What is your github Username?'},

    {name: 'email',
    type: 'input',
    message: 'What is your email address?'},

    {name: 'description',
    type: 'input',
    message: 'What is your project description?'},

    {name: 'contributing',
    type: 'input',
    message: 'What are the expectations of contributors in terms of behavior?'},
    
    {name: 'installation',
    type: 'input',
    message: 'How does project installation work?'},

    {name: 'tests',
    type: 'input',
    message: 'How do you run tests?'},

    {name: 'usage',
    type: 'input',
    message: 'Describe how to use the project'},

    {name: 'license',
     type: 'list',
     message: 'What licence do you want?',
     choices: licenseChoices}
];

const meh = []

// function to write README file
function writeToFile(fileName, data) {

    let dirname = path.dirname(fileName)
    fs.mkdir(dirname, {recursive:true}, function(mkdirerr) {
        if(mkdirerr) {
            console.error("mkdir failed with: + " + mkdirerr)
        }
        fs.writeFile(fileName, data, function(err){
            if(err) {
                console.error("writeFile blew up saying:" + err)
                throw err
            }
        })
    });
}

// function to initialize program
function init() {
    const answers = inquirer.prompt(questions)
    answers.then(function(answers){
       let licenseIndex = licenseChoices.findIndex(i => i===answers.license)
       let fullLicense = licenceOptions[licenseIndex]
       var markdownData = {
           title: answers.title,
           description: answers.description,
           tests: answers.tests,
           usage: answers.usage,
           contributing: answers.contributing,
           installation: answers.installation,
           email: answers.email,
           githubUsername: answers.githubUser,
           license: fullLicense,
       }
       let markdownText = generateMarkdown(markdownData)
       writeToFile("./dumping_ground/README.md", markdownText)
   })

}

function play() {
    var sampleMarkdownData = {
        title: "the title",
        license: {
            name:    'BSD 2-Clause License',
            badge:     'https://img.shields.io/badge/License-BSD%202--Clause-orange.svg',
            summary:   'bsd 2.0 summary',
            linkToMoreInfo:'https://opensource.org/licenses/BSD-2-Clause'},
        description: "the description",
        installation: "installation steps",
        usage: "usage",
        contributing: "This is a critically UNSAFE ZONE for SJWs.  Any proposals of Terminology warfare will result in cruel and brutal ostracization.  By engaging with 'the community' involved in this software, you either implicitly agree not to be a filthy SJW or you will at least not behave as one in any discussion.  You are strongly encouraged to savagely berate all such people and to spit on them and maybe physically assault them for bonus points.  Such people are revolting, we judge them harshly, and we dilligently and deliberately purge them from our ranks.  Also, use the words master and slave at every opportunity.",
        tests: "test instructions",
        githubUsername: "githubUsername",
        email: "a@b.com"
      }
      
    let markdownText = generateMarkdown(sampleMarkdownData)
    //console.log("markdown: " + markdownText)

    writeToFile("./dumping_ground/README.md", markdownText)
}

// function call to initialize program
init();
//play();
